spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
---
springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
    path: '/v3/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'
    config-url: '/v3/api-docs/swagger-config'
    url: '/v3/api-docs'
    doc-expansion: none
    disable-swagger-default-url: true
